export const stationOrder = 'alphabetical';

export const stationList = [
  {
    name: '12th St. Oakland',
    abbr: '12TH',
    latitude: '37.803768',
    longitude: '-122.271450',
    direction: '',
    visits: 0,
    northStations: ['19TH'],
    southStations: ['WOAK', 'LAKE'],
  },
  {
    name: '16th St. Mission',
    abbr: '16TH',
    latitude: '37.765062',
    longitude: '-122.419694',
    direction: '',
    visits: 0,
    northStations: ['CIVC'],
    southStations: ['24TH'],
  },
  {
    name: '19th St. Oakland',
    abbr: '19TH',
    latitude: '37.808350',
    longitude: '-122.268602',
    direction: '',
    visits: 0,
    northStations: ['MCAR'],
    southStations: ['12TH'],
  },
  {
    name: '24th St. Mission',
    abbr: '24TH',
    latitude: '37.752470',
    longitude: '-122.418143',
    direction: '',
    visits: 0,
    northStations: ['16TH'],
    southStations: ['GLEN'],
  },
  {
    name: 'Ashby',
    abbr: 'ASHB',
    latitude: '37.852803',
    longitude: '-122.270062',
    direction: '',
    visits: 0,
    northStations: ['DBRK'],
    southStations: ['MCAR'],
  },
  {
    name: 'Balboa Park',
    abbr: 'BALB',
    latitude: '37.721585',
    longitude: '-122.447506',
    direction: '',
    visits: 0,
    northStations: ['GLEN'],
    southStations: ['COLM'],
  },
  {
    name: 'Bay Fair',
    abbr: 'BAYF',
    latitude: '37.696924',
    longitude: '-122.126514',
    direction: '',
    visits: 0,
    northStations: ['SANL'],
    southStations: ['HAYW', 'CAST'],
  },
  {
    name: 'Castro Valley',
    abbr: 'CAST',
    latitude: '37.690746',
    longitude: '-122.075602',
    direction: '',
    visits: 0,
    northStations: ['BAYF'],
    southStations: ['WDUB'],
  },
  {
    name: 'Civic Center/UN Plaza',
    abbr: 'CIVC',
    latitude: '37.779732',
    longitude: '-122.414123',
    direction: '',
    visits: 0,
    northStations: ['POWL'],
    southStations: ['16TH'],
  },
  {
    name: 'Coliseum',
    abbr: 'COLS',
    latitude: '37.753661',
    longitude: '-122.196869',
    direction: '',
    visits: 0,
    northStations: ['FTVL'],
    southStations: ['OAKL', 'SANL'],
  },
  {
    name: 'Colma',
    abbr: 'COLM',
    latitude: '37.684638',
    longitude: '-122.466233',
    direction: '',
    visits: 0,
    northStations: ['DALY'],
    southStations: ['SSAN'],
  },
  {
    name: 'Concord',
    abbr: 'CONC',
    latitude: '37.973737',
    longitude: '-122.029095',
    direction: '',
    visits: 0,
    northStations: ['NCON'],
    southStations: ['PHIL'],
  },
  {
    name: 'Daly City',
    abbr: 'DALY',
    latitude: '37.70612055',
    longitude: '-122.4690807',
    direction: '',
    visits: 0,
    northStations: ['BALB'],
    southStations: ['COLM'],
  },
  {
    name: 'Downtown Berkeley',
    abbr: 'DBRK',
    latitude: '37.870104',
    longitude: '-122.268133',
    direction: '',
    visits: 0,
    northStations: ['NBRK'],
    southStations: ['ASHB'],
  },
  {
    name: 'Dublin/Pleasanton',
    abbr: 'DUBL',
    latitude: '37.701687',
    longitude: '-121.899179',
    direction: '',
    visits: 0,
    northStations: ['WDUB'],
    southStations: [],
  },
  {
    name: 'El Cerrito del Norte',
    abbr: 'DELN',
    latitude: '37.925086',
    longitude: '-122.316794',
    direction: '',
    visits: 0,
    northStations: ['RICH'],
    southStations: ['PLZA'],
  },
  {
    name: 'El Cerrito Plaza',
    abbr: 'PLZA',
    latitude: '37.902632',
    longitude: '-122.298904',
    direction: '',
    visits: 0,
    northStations: ['DELN'],
    southStations: ['NBRK'],
  },
  {
    name: 'Embarcadero',
    abbr: 'EMBR',
    latitude: '37.792874',
    longitude: '-122.397020',
    direction: '',
    visits: 0,
    northStations: ['WOAK'],
    southStations: ['MONT'],
  },
  {
    name: 'Fremont',
    abbr: 'FRMT',
    latitude: '37.557465',
    longitude: '-121.976608',
    direction: '',
    visits: 0,
    northStations: ['UCTY'],
    southStations: ['WARM'],
  },
  {
    name: 'Fruitvale',
    abbr: 'FTVL',
    latitude: '37.774836',
    longitude: '-122.224175',
    direction: '',
    visits: 0,
    northStations: ['LAKE'],
    southStations: ['COLS'],
  },
  {
    name: 'Glen Park',
    abbr: 'GLEN',
    latitude: '37.733064',
    longitude: '-122.433817',
    direction: '',
    visits: 0,
    northStations: ['24TH'],
    southStations: ['BALB'],
  },
  {
    name: 'Hayward',
    abbr: 'HAYW',
    latitude: '37.669723',
    longitude: '-122.087018',
    direction: '',
    visits: 0,
    northStations: ['BAYF'],
    southStations: ['SHAY'],
  },
  {
    name: 'Lafayette',
    abbr: 'LAFY',
    latitude: '37.893176',
    longitude: '-122.124630',
    direction: '',
    visits: 0,
    northStations: ['WCRK'],
    southStations: ['ORIN'],
  },
  {
    name: 'Lake Merritt',
    abbr: 'LAKE',
    latitude: '37.797027',
    longitude: '-122.265180',
    direction: '',
    visits: 0,
    northStations: ['12TH', 'WOAK'],
    southStations: ['FTVL'],
  },
  {
    name: 'MacArthur',
    abbr: 'MCAR',
    latitude: '37.829065',
    longitude: '-122.267040',
    direction: '',
    visits: 0,
    northStations: ['ASHB', 'ROCK'],
    southStations: ['19TH'],
  },
  {
    name: 'Millbrae',
    abbr: 'MLBR',
    latitude: '37.600271',
    longitude: '-122.386702',
    direction: '',
    visits: 0,
    northStations: ['SBRN', 'SFIA'],
    southStations: [],
  },
  {
    name: 'Montgomery St.',
    abbr: 'MONT',
    latitude: '37.789405',
    longitude: '-122.401066',
    direction: '',
    visits: 0,
    northStations: ['EMBR'],
    southStations: ['POWL'],
  },
  {
    name: 'North Berkeley',
    abbr: 'NBRK',
    latitude: '37.873967',
    longitude: '-122.283440',
    direction: '',
    visits: 0,
    northStations: ['PLZA'],
    southStations: ['DBRK'],
  },
  {
    name: 'North Concord/Martinez',
    abbr: 'NCON',
    latitude: '38.003193',
    longitude: '-122.024653',
    direction: '',
    visits: 0,
    northStations: ['PITT'],
    southStations: ['CONC'],
  },
  {
    name: "Oakland Int'l Airport",
    abbr: 'OAKL',
    latitude: '37.713238',
    longitude: '-122.212191',
    direction: '',
    visits: 0,
    northStations: ['COLS'],
    southStations: [],
  },
  {
    name: 'Orinda',
    abbr: 'ORIN',
    latitude: '37.87836087',
    longitude: '-122.1837911',
    direction: '',
    visits: 0,
    northStations: ['LAFY'],
    southStations: ['ROCK'],
  },
  {
    name: 'Pittsburg/Bay Point',
    abbr: 'PITT',
    latitude: '38.018914',
    longitude: '-121.945154',
    direction: '',
    visits: 0,
    northStations: [],
    southStations: ['NCON'],
  },
  {
    name: 'Pleasant Hill',
    abbr: 'PHIL',
    latitude: '37.928468',
    longitude: '-122.056012',
    direction: '',
    visits: 0,
    northStations: ['CONC'],
    southStations: ['WCRK'],
  },
  {
    name: 'Powell St.',
    abbr: 'POWL',
    latitude: '37.784471',
    longitude: '-122.407974',
    direction: '',
    visits: 0,
    northStations: ['MONT'],
    southStations: ['CIVC'],
  },
  {
    name: 'Richmond',
    abbr: 'RICH',
    latitude: '37.936853',
    longitude: '-122.353099',
    direction: '',
    visits: 0,
    northStations: [],
    southStations: ['DELN'],
  },
  {
    name: 'Rockridge',
    abbr: 'ROCK',
    latitude: '37.844702',
    longitude: '-122.251371',
    direction: '',
    visits: 0,
    northStations: ['ORIN'],
    southStations: ['MCAR'],
  },
  {
    name: 'San Bruno',
    abbr: 'SBRN',
    latitude: '37.637761',
    longitude: '-122.416287',
    direction: '',
    visits: 0,
    northStations: ['SSAN'],
    southStations: ['SFIA', 'MLBR'],
  },
  {
    name: "San Fran Int'l Airport",
    abbr: 'SFIA',
    latitude: '37.615966',
    longitude: '-122.392409',
    direction: '',
    visits: 0,
    northStations: ['SBRN'],
    southStations: ['MLBR'],
  },
  {
    name: 'San Leandro',
    abbr: 'SANL',
    latitude: '37.721947',
    longitude: '-122.160844',
    direction: '',
    visits: 0,
    northStations: ['COLS'],
    southStations: ['BAYF'],
  },
  {
    name: 'South Hayward',
    abbr: 'SHAY',
    latitude: '37.634375',
    longitude: '-122.057189',
    direction: '',
    visits: 0,
    northStations: ['HAYW'],
    southStations: ['UCTY'],
  },
  {
    name: 'South San Francisco',
    abbr: 'SSAN',
    latitude: '37.664245',
    longitude: '-122.443960',
    direction: '',
    visits: 0,
    northStations: ['COLM'],
    southStations: ['SBRN'],
  },
  {
    name: 'Union City',
    abbr: 'UCTY',
    latitude: '37.590630',
    longitude: '-122.017388',
    direction: '',
    visits: 0,
    northStations: ['HAYW'],
    southStations: ['UCTY'],
  },
  {
    name: 'Walnut Creek',
    abbr: 'WCRK',
    latitude: '37.905522',
    longitude: '-122.067527',
    direction: '',
    visits: 0,
    northStations: ['PHIL'],
    southStations: ['LAFY'],
  },
  {
    name: 'West Dublin/Pleasanton',
    abbr: 'WDUB',
    latitude: '37.699756',
    longitude: '-121.928240',
    direction: '',
    visits: 0,
    northStations: ['CAST'],
    southStations: ['DUBL'],
  },
  {
    name: 'West Oakland',
    abbr: 'WOAK',
    latitude: '37.804872',
    longitude: '-122.295140',
    direction: '',
    visits: 0,
    northStations: ['12TH', 'LAKE'],
    southStations: ['EMBR'],
  },
  {
    name: 'Warm Springs',
    abbr: 'WARM',
    latitude: '37.502171',
    longitude: '-121.939313',
    direction: '',
    visits: 0,
    northStations: ['FRMT'],
    southStations: [],
  },
];
